# Prosper Loan Data Exploration

### Yagmur Dalman

## Preliminary Wrangling

This data set contains 113,937 loans with 81 variables on each loan, including loan amount, borrower rate (or interest rate), current loan status, borrower income, and many others. I choose 14 variables for my analysis.


In [591]:
# import all packages and set plots to be embedded inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

%matplotlib inline

In [592]:
# load in the dataset into a pandas dataframe, print statistics

df = pd.read_csv('prosperLoanData.csv')
df.head()

ListingKey  ListingNumber            ListingCreationDate  \
0  1021339766868145413AB3B         193129  2007-08-26 19:09:29.263000000   
1  10273602499503308B223C1        1209647  2014-02-27 08:28:07.900000000   
2  0EE9337825851032864889A          81716  2007-01-05 15:00:47.090000000   
3  0EF5356002482715299901A         658116  2012-10-22 11:02:35.010000000   
4  0F023589499656230C5E3E2         909464  2013-09-14 18:38:39.097000000   

  CreditGrade  Term LoanStatus           ClosedDate  BorrowerAPR  \
0           C    36  Completed  2009-08-14 00:00:00      0.16516   
1         NaN    36    Current                  NaN      0.12016   
2          HR    36  Completed  2009-12-17 00:00:00      0.28269   
3         NaN    36    Current                  NaN      0.12528   
4         NaN    36    Current                  NaN      0.24614   

   BorrowerRate  LenderYield    ...     LP_ServiceFees  LP_CollectionFees  \
0        0.1580       0.1380    ...            -133.18                0.0   
1        0.0920       0.0820    ...               0.00                0.0   
2        0.2750       0.2400    ...             -24.20                0.0   
3        0.0974       0.0874    ...            -108.01                0.0   
4        0.2085       0.1985    ...             -60.27                0.0   

   LP_GrossPrincipalLoss  LP_NetPrincipalLoss LP_NonPrincipalRecoverypayments  \
0                    0.0                  0.0                             0.0   
1                    0.0                  0.0                             0.0   
2                    0.0                  0.0                             0.0   
3                    0.0                  0.0                             0.0   
4                    0.0                  0.0                             0.0   

   PercentFunded  Recommendations InvestmentFromFriendsCount  \
0            1.0                0                          0   
1            1.0                0                          0   
2            1.0                0                          0   
3            1.0                0                          0   
4            1.0                0                          0   

  InvestmentFromFriendsAmount Investors  
0                         0.0       258  
1                         0.0         1  
2                         0.0        41  
3                         0.0       158  
4                         0.0        20  

[5 rows x 81 columns]

In [593]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113937 entries, 0 to 113936
Data columns (total 81 columns):
ListingKey                             113937 non-null object
ListingNumber                          113937 non-null int64
ListingCreationDate                    113937 non-null object
CreditGrade                            28953 non-null object
Term                                   113937 non-null int64
LoanStatus                             113937 non-null object
ClosedDate                             55089 non-null object
BorrowerAPR                            113912 non-null float64
BorrowerRate                           113937 non-null float64
LenderYield                            113937 non-null float64
EstimatedEffectiveYield                84853 non-null float64
EstimatedLoss                          84853 non-null float64
EstimatedReturn                        84853 non-null float64
ProsperRating (numeric)                84853 non-null float64
ProsperRating (Alpha) 

In [594]:
# check duplicates 
df.duplicated().sum()

0

In [595]:
# the columns will be used in the analysis
columns = ['Term','LoanStatus', 'BorrowerAPR','ProsperScore','ListingCategory (numeric)',
           'ProsperRating (numeric)','BorrowerState', 'Occupation',
           'EmploymentStatus','IsBorrowerHomeowner', 'LoanOriginalAmount',
           'DelinquenciesLast7Years', 'DebtToIncomeRatio','StatedMonthlyIncome']
# take the needed columns
df = df[columns]
# drop the rows with missing value 
df.dropna(inplace = True)


In [596]:
# rename some of the columns to match the style
df.rename(columns = {'ProsperRating (numeric)':'ProsperRatingNumeric',
                     'ListingCategory (numeric)': 'ListingCategoryNumeric'}, inplace = True)


In [597]:
# overview of data
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 76224 entries, 1 to 113936
Data columns (total 14 columns):
Term                       76224 non-null int64
LoanStatus                 76224 non-null object
BorrowerAPR                76224 non-null float64
ProsperScore               76224 non-null float64
ListingCategoryNumeric     76224 non-null int64
ProsperRatingNumeric       76224 non-null float64
BorrowerState              76224 non-null object
Occupation                 76224 non-null object
EmploymentStatus           76224 non-null object
IsBorrowerHomeowner        76224 non-null bool
LoanOriginalAmount         76224 non-null int64
DelinquenciesLast7Years    76224 non-null float64
DebtToIncomeRatio          76224 non-null float64
StatedMonthlyIncome        76224 non-null float64
dtypes: bool(1), float64(6), int64(3), object(4)
memory usage: 8.2+ MB


In [599]:
df.head()

Term LoanStatus  BorrowerAPR  ProsperScore  ListingCategoryNumeric  \
1    36    Current      0.12016           7.0                       2   
3    36    Current      0.12528           9.0                      16   
4    36    Current      0.24614           4.0                       2   
5    60    Current      0.15425          10.0                       1   
6    36    Current      0.31032           2.0                       1   

   ProsperRatingNumeric BorrowerState      Occupation EmploymentStatus  \
1                   6.0            CO    Professional         Employed   
3                   6.0            GA   Skilled Labor         Employed   
4                   3.0            MN       Executive         Employed   
5                   5.0            NM    Professional         Employed   
6                   2.0            KS  Sales - Retail         Employed   

   IsBorrowerHomeowner  LoanOriginalAmount  DelinquenciesLast7Years  \
1                False               10000                      0.0   
3                 True               10000                     14.0   
4                 True               15000                      0.0   
5                 True               15000                      0.0   
6                False                3000                      0.0   

   DebtToIncomeRatio  StatedMonthlyIncome  
1               0.18          6125.000000  
3               0.15          2875.000000  
4               0.26          9583.333333  
5               0.36          8333.333333  
6               0.27          2083.333333

In [600]:
# check for erroneous data
print(df.ProsperScore.unique())
print(df.ListingCategoryNumeric.unique())
print(df.ProsperRatingNumeric.unique())

[ 7.  9.  4. 10.  2. 11.  8.  5.  3.  6.  1.]
[ 2 16  1  7 13  6 15 20 19 18  8 11  3 14  9 17  0 10  5 12]
[6. 3. 5. 2. 4. 7. 1.]


There is no prosper score such 11 according to the data dictionary but in the Prosper website it is stated that  Prosper score ranges from 1 to 11, with 11 being the best, or lowest risk, score. So I will keep them.
https://www.prosper.com/plp/general-prosper_score/